/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class persona (private val name: String) {
    val saludo: String
        get() {
            return "Hola $name !"
        }
}

fun main() {
    println("Cual es tu nombre?: ")
    val nombre = readLine() ?: "desconocido"
    val a = persona(nombre)
    println(a.saludo)
}
